<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xaw.jammazwan/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="XawServiceService" targetNamespace="http://xaw.jammazwan/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xaw.jammazwan/" elementFormDefault="unqualified" targetNamespace="http://xaw.jammazwan/" version="1.0">

  <xs:element name="noChange" type="tns:noChange"/>

  <xs:element name="noChangeResponse" type="tns:noChangeResponse"/>

  <xs:complexType name="noChange">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="noChangeResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="noChange">
    <wsdl:part element="tns:noChange" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="noChangeResponse">
    <wsdl:part element="tns:noChangeResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="XawService">
    <wsdl:operation name="noChange">
      <wsdl:input message="tns:noChange" name="noChange">
    </wsdl:input>
      <wsdl:output message="tns:noChangeResponse" name="noChangeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="XawServiceServiceSoapBinding" type="tns:XawService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="noChange">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="noChange">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="noChangeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="XawServiceService">
    <wsdl:port binding="tns:XawServiceServiceSoapBinding" name="XawServicePort">
      <soap:address location="http://localhost:9875/passThru/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>