package jammazwan.xaw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-17T09:14:47.085-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://xaw.jammazwan/", name = "XawService")
@XmlSeeAlso({ObjectFactory.class})
public interface XawService {

    @WebMethod
    @RequestWrapper(localName = "noChange", targetNamespace = "http://xaw.jammazwan/", className = "jammazwan.xaw.NoChange")
    @ResponseWrapper(localName = "noChangeResponse", targetNamespace = "http://xaw.jammazwan/", className = "jammazwan.xaw.NoChangeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String noChange(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
