
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package jammazwan.xaw;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-17T09:14:47.056-05:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "XawServiceService",
                      portName = "XawServicePort",
                      targetNamespace = "http://xaw.jammazwan/",
                      wsdlLocation = "classpath:wsdl/passThru.wsdl",
                      endpointInterface = "jammazwan.xaw.XawService")
                      
public class XawServicePortImpl implements XawService {

    private static final Logger LOG = Logger.getLogger(XawServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see jammazwan.xaw.XawService#noChange(java.lang.String  arg0 )*
     */
    public java.lang.String noChange(java.lang.String arg0) { 
        LOG.info("Executing operation noChange");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
