package jammazwan.xaw;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-17T09:14:47.089-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "XawServiceService", 
                  wsdlLocation = "classpath:wsdl/passThru.wsdl",
                  targetNamespace = "http://xaw.jammazwan/") 
public class XawServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xaw.jammazwan/", "XawServiceService");
    public final static QName XawServicePort = new QName("http://xaw.jammazwan/", "XawServicePort");
    static {
        URL url = XawServiceService.class.getClassLoader().getResource("wsdl/passThru.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(XawServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/passThru.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public XawServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XawServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XawServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public XawServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XawServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XawServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns XawService
     */
    @WebEndpoint(name = "XawServicePort")
    public XawService getXawServicePort() {
        return super.getPort(XawServicePort, XawService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XawService
     */
    @WebEndpoint(name = "XawServicePort")
    public XawService getXawServicePort(WebServiceFeature... features) {
        return super.getPort(XawServicePort, XawService.class, features);
    }

}
